;(function(){var dfltPluginCfg={"sourceFile":"download","info":true};var dfltGlobalCfg={"site":568621,"log":"logc407","logSSL":"logs1407","domain":"xiti.com","secure":false,"pixelPath":"/hit.xiti","disableCookie":false,"cookieSecure":false,"cookieDomain":"","preview":false,"plgs":["Campaigns","Clicks","ClientSideUserId","ContextVariables","IdentifiedVisitor","InternalSearch","OnSiteAds","Page","SalesTracker"],"lazyLoadingPath":"","documentLevel":"document","redirect":false,"activateCallbacks":true,"medium":"","ignoreEmptyChapterValue":true,"base64Storage":false};(function(a,c){a.ATInternet=a.ATInternet||{};a.ATInternet.Tracker=a.ATInternet.Tracker||{};a.ATInternet.Tracker.Plugins=a.ATInternet.Tracker.Plugins||{}})(window);
var Utils=function(){function a(h){var m=typeof h;if("object"!==m||null===h)return"string"===m&&(h='"'+h+'"'),String(h);var g,b,n=[],d=h&&h.constructor===Array;for(g in h)h.hasOwnProperty(g)&&(b=h[g],m=typeof b,"function"!==m&&"undefined"!==m&&("string"===m?b='"'+b.replace(/[^\\]"/g,'\\"')+'"':"object"===m&&null!==b&&(b=a(b)),n.push((d?"":'"'+g+'":')+String(b))));return(d?"[":"{")+String(n)+(d?"]":"}")}var c=this;c.cloneSimpleObject=function m(a,b){if("object"!==typeof a||null===a||a instanceof Date)return a;
var n=new a.constructor||a.constructor(),d;for(d in a)a.hasOwnProperty(d)&&(void 0===d||b&&void 0===a[d]||(n[d]=m(a[d])));return n};c.jsonSerialize=function(m){return"undefined"!==typeof JSON&&JSON.stringify?JSON.stringify(m):a(m)};c.jsonParse=function(a){try{if("undefined"!==typeof JSON&&JSON.parse)return JSON.parse(a);var g;g=null===a?a:"string"===typeof a?(new Function("return "+a))():!1;return g}catch(b){return null}};c.arrayIndexOf=function(a,g){return Array.indexOf?a.indexOf(g):function(a){if(null==
this)throw new TypeError;var n=Object(this),d=n.length>>>0;if(0===d)return-1;var f=0;1<arguments.length&&(f=Number(arguments[1]),f!=f?f=0:0!=f&&Infinity!=f&&-Infinity!=f&&(f=(0<f||-1)*Math.floor(Math.abs(f))));if(f>=d)return-1;for(f=0<=f?f:Math.max(d-Math.abs(f),0);f<d;f++)if(f in n&&n[f]===a)return f;return-1}.apply(a,[g])};c.uuid=function(){return{v4:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var g=16*Math.random()|0;return("x"===a?g:g&3|8).toString(16)})},
num:function(a){var g=new Date,b=function(a){a-=100*Math.floor(a/100);return 10>a?"0"+a:a};return b(g.getHours())+""+b(g.getMinutes())+""+b(g.getSeconds())+""+function(a){return Math.floor((9*Math.random()+1)*Math.pow(10,a-1))}(a-6)}}};c.getObjectKeys=function(a){var g=[],b;for(b in a)a.hasOwnProperty(b)&&g.push(b);return g};c.completeFstLevelObj=function(a,g,b){if(a){if(g)for(var n in g)!g.hasOwnProperty(n)||a[n]&&!b||(a[n]=g[n])}else a=g;return a};c.isPreview=function(){return window.navigator&&
"preview"===window.navigator.loadPurpose};c.isPrerender=function(a){var g,b=!1,n=["webkit","ms"];if("prerender"===document.visibilityState)g="visibilitychange";else for(var d=0;d<n.length;d++)"prerender"===document[n[d]+"VisibilityState"]&&(g=n[d]+"visibilitychange");if("undefined"!==typeof g){var f=function(b){a(b);c.removeEvtListener(document,g,f)};c.addEvtListener(document,g,f);b=!0}return b};var k=c.addEvtListener=function(a,g,b){a.addEventListener?a.addEventListener(g,b,!1):a.attachEvent&&a.attachEvent("on"+
g,b)},e=c.removeEvtListener=function(a,g,b){a.removeEventListener?a.removeEventListener(g,b,!1):a.detachEvent&&a.detachEvent("on"+g,b)};c.loadScript=function(a,g){var b;g=g||function(){};b=document.createElement("script");b.type="text/javascript";b.src=a.url;b.async=!1;b.defer=!1;b.onload=b.onreadystatechange=function(a){a=a||window.event;if("load"===a.type||/loaded|complete/.test(b.readyState)&&(!document.documentMode||9>document.documentMode))b.onload=b.onreadystatechange=b.onerror=null,g(null,
a)};b.onerror=function(a,f,n){b.onload=b.onreadystatechange=b.onerror=null;g({msg:"script not loaded",event:a})};var n=document.head||document.getElementsByTagName("head")[0];n.insertBefore(b,n.lastChild)};c.hashcode=function(a){var g=0;if(0===a.length)return g;for(var b=0;b<a.length;b++)var n=a.charCodeAt(b),g=(g<<5)-g+n,g=g&g;return g};c.setLocation=function(a){var g=a.location;a=window[a.target]||window;g&&(a.location.href=g)};c.dispatchCallbackEvent=function(a){var g;"function"===typeof window.Event?
g=new Event("ATCallbackEvent"):(g=document.createEvent("Event"),g.initEvent&&g.initEvent("ATCallbackEvent",!0,!0));g&&(g.name=a,document.dispatchEvent(g))};c.addCallbackEvent=function(a){k(document,"ATCallbackEvent",a)};(function(){function a(g,b){b=b||{bubbles:!1,cancelable:!1,detail:void 0};var n=document.createEvent("CustomEvent");n.initCustomEvent(g,b.bubbles,b.cancelable,b.detail);return n}if("function"===typeof window.CustomEvent)return!1;a.prototype=window.Event.prototype;window.CustomEvent=
a})();c.addOptOutEvent=function(a,g){c.ATOptOutEvent=new CustomEvent("ATOptOutEvent",{detail:{name:"clientsideuserid",id:g}});k(document,"ATOptOutEvent",a)};c.removeOptOutEvent=function(a){e(document,"ATOptOutEvent",a)};c.dispatchOptOutEvent=function(a){c.optedOut=a;c.ATOptOutEvent=c.ATOptOutEvent||new CustomEvent("ATOptOutEvent",{detail:{name:"clientsideuserid",id:-1}});document.dispatchEvent(c.ATOptOutEvent)};c.userOptedOut=function(){c.dispatchOptOutEvent(!0)};c.userOptedIn=function(){c.dispatchOptOutEvent(!1)};
c.isOptedOut=function(){return!!c.optedOut};c.optedOut=null;c.ATOptOutEvent=null};window.ATInternet.Utils=new Utils;
var BuildManager=function(a){var c=this,k=function(a,b,f){a="&"+a+"=";return{param:a,paramSize:a.length,str:b,strSize:b.length,truncate:f}},e=function(b,d){var f="",h=0,g=!0,l;for(l in b)if(b.hasOwnProperty(l)){var p=b[l];if(p){var g=!1,c=d-h;if(p.strSize+p.paramSize<c)f+=p.param+p.str,h+=p.strSize+p.paramSize,b[l]=void 0,g=!0;else{p.truncate?(f+=p.param+p.str.substr(0,c),b[l].str=p.str.substr(c,p.strSize-1),b[l].strSize=b[l].str.length):p.strSize+p.paramSize>d&&(a.emit("Tracker:Hit:Build:Error",
{lvl:"ERROR",msg:'Too long parameter "'+p.param+'"',details:{value:p.str}}),b[l].str=b[l].str.substr(0,d-p.paramSize-1),b[l].strSize=b[l].str.length);break}}else g=!0}return[f,g?null:b]},h=["ati","atc","pdtl","stc","dz"],m=function(b,d,f){var g=function(a){if(a==={})return"";var b=[],l;l={};var f=0,d=!1,g=void 0,c,n,q;for(q in a)if(a.hasOwnProperty(q)){var r=a[q].value;"function"===typeof r&&(r=r());r=r instanceof Array?r.join(a[q].options.separator||","):"object"===typeof r?window.ATInternet.Utils.jsonSerialize(r):
"undefined"===typeof r?"undefined":r.toString();a[q].options.encode&&(r=encodeURIComponent(r));var m=k(q,r,-1<window.ATInternet.Utils.arrayIndexOf(h,q)),f=f+(m.paramSize+m.strSize);if(a[q].options.last)1490<r.length&&r.substr(0,1490),c=q,n=m;else if(l[q]=m,1500<l[q].paramSize+l[q].strSize&&!l[q].truncate){d=!0;g=q;break}}c&&(l[c]=n);l=[l,f,d,g];a=l[0];if(l[2])l=l[3],a=a[l],a.str=a.str.substr(0,1450),a.strSize=1450,f={},f.mherr=k("mherr","1",!1),f[l]=a,b.push(e(f,1500)[0]);else if(l=e(a,1500),null===
l[1])b=l[0];else for(b.push(l[0]);null!==l[1];)l=e(a,1500),b.push(l[0]);return b},c="";a.buffer.presentInFilters(d,"hitType")||(d=a.buffer.addInFilters(d,"hitType",["page"]));d=a.buffer.addInFilters(d,"hitType",["all"]);var l;if(b){d=a.buffer.addInFilters(d,"permanent",!0);d=a.buffer.get(d,!0);for(l in b)b.hasOwnProperty(l)&&(d[l]={value:b[l],options:{}});c=g(d)}else for(l in d=a.buffer.get(d,!0),c=g(d),d)d.hasOwnProperty(l)&&!d[l].options.permanent&&a.buffer.del(l);f&&f(c)},g=function(b){var d=a.getConfig("secure"),
f="https:"===document.location.protocol,f=d||f?a.getConfig("logSSL"):a.getConfig("log"),h=a.getConfig("baseURL"),g=a.getConfig("domain"),l=a.getConfig("pixelPath"),p=a.getConfig("site");(h||f&&g&&l)&&p?b&&b(null,(h?h:(d?"https://":"//")+f+("."+g)+l)+("?s="+p)):b&&b({message:"Config error"})},b=function(a,b,f){g(function(h,g){h?f&&f(h):m(a,b,function(a){var b=[],d=ATInternet.Utils.uuid().num(13);if(a instanceof Array)if(1===a.length)b.push(g+"&mh=1-2-"+d+a[0]);else for(var h=1;h<=a.length;h++)b.push(g+
"&mh="+h+"-"+a.length+"-"+d+a[h-1]);else b.push(g+a);f&&f(null,b)})})};c.send=function(h,d){b(h,d,function(b,d){if(b)a.emit("Tracker:Hit:Build:Error",{lvl:"ERROR",msg:b.message,details:{hits:d}});else for(var h=0;h<d.length;h++)c.sendUrl(d[h])})};c.sendUrl=function(b){var d=function(b,f){return function(){return function(l){a.emit(b,{lvl:-1===b.indexOf("Error")?"INFO":"ERROR",details:{hit:f,event:l}})}}()},f=new Image;f.onload=d("Tracker:Hit:Sent:Ok",b);f.onerror=d("Tracker:Hit:Sent:Error",b);f.src=
b}},TriggersManager=function(){function a(a,c,g){for(var b=[],e=0;e<a.length;e++)a[e].callback(c,g),a[e].singleUse||b.push(a[e]);return b}function c(a,e,g,b){var n=a.shift();if("*"===n)return e["*"]=e["*"]||[],e["*"].push({callback:g,singleUse:b}),e["*"].length-1;if(0===a.length)return c([n,"*"],e,g,b);e["*"]=e["*"]||[];e[n]=e[n]||{};return c(a,e[n],g,b)}function k(h,c,g,b){var e=c.shift();"*"!==e&&(0===c.length?k(h,[e,"*"],g,b):g[e]&&(g[e]["*"]=a(g[e]["*"],h,b),k(h,c,g[e],b)))}var e={};this.on=function(a,
m,g){g=g||!1;return c(a.split(":"),e,m,g)};this.emit=function(h,c){e["*"]&&(e["*"]=a(e["*"],h,c));k(h,h.split(":"),e,c)}},PluginsManager=function(a){var c={},k={},e=0,h={},m=0,g=this.load=function(l,f){"function"===typeof f?"undefined"===typeof a.getConfig.plgAllowed||0===a.getConfig.plgAllowed.length||-1<a.getConfig.plgAllowed.indexOf(l)?(c[l]=new f(a),k[l]&&c[l]&&(k[l]=!1,e--,c[l+"_ll"]&&b(l+"_ll"),0===e&&a.emit("Tracker:Plugin:Lazyload:File:Complete",{lvl:"INFO",msg:"LazyLoading triggers are finished"})),
a.emit("Tracker:Plugin:Load:"+l+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Load:"+l+":Error",{lvl:"ERROR",msg:"Plugin not allowed",details:{}}):a.emit("Tracker:Plugin:Load:"+l+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:f}});return a},b=this.unload=function(b){c[b]?(c[b]=void 0,a.emit("Tracker:Plugin:Unload:"+b+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Unload:"+b+":Error",{lvl:"ERROR",msg:"not a known plugin"});return a},n=this.isLazyloading=function(a){return a?!0===k[a]:0!==e},d=
function(a){return r(a)?(f(a),!0):!1},f=function(b){k[b]=!0;e++;ATInternet.Utils.loadScript({url:a.getConfig("lazyLoadingPath")+b+".js"})},r=function(a){return!c[a]&&!n(a)&&(c[a+"_ll"]?!0:!1)},q=function(a){h[a]?h[a]++:h[a]=1;m++};this.isExecWaitingLazyloading=function(){return 0!==m};a.exec=this.exec=function(b,p,d,g){var e=null,k=function(a,b,f,l){b=b.split(".");c[a]&&c[a][b[0]]&&(e=1<b.length&&c[a][b[0]][b[1]]?c[a][b[0]][b[1]].apply(c[a],f):c[a][b[0]].apply(c[a],f));l&&l(e)},v=function(b,f,l,p){q(b);
a.onTrigger("Tracker:Plugin:Load:"+b+":Ok",function(){k(b,f,l,function(f){h[b]--;m--;0===m&&a.emit("Tracker:Plugin:Lazyload:Exec:Complete",{lvl:"INFO",msg:"All exec waiting for lazyloading are done"});p&&p(f)})},!0)};r(b)?(v(b,p,d,g),f(b)):n(b)?v(b,p,d,g):k(b,p,d,g)};this.waitForDependencies=function(b,f){var g=function(a){for(var b={mcount:0,plugins:{}},f=0;f<a.length;f++)c.hasOwnProperty(a[f])||(b.mcount++,b.plugins[a[f]]=!0);return b}(b);if(0===g.mcount)a.emit("Tracker:Plugin:Dependencies:Loaded",
{lvl:"INFO",details:{dependencies:b}}),f();else for(var h in g.plugins)g.plugins.hasOwnProperty(h)&&(a.emit("Tracker:Plugin:Dependencies:Error",{lvl:"WARNING",msg:"Missing plugin "+h}),a.onTrigger("Tracker:Plugin:Load:"+h,function(a,b){var l=a.split(":"),d=l[3];"Ok"===l[4]&&(g.plugins[d]=!1,g.mcount--,0===g.mcount&&f())},!0),d(h))};this.init=function(){for(var a in ATInternet.Tracker.pluginProtos)ATInternet.Tracker.pluginProtos.hasOwnProperty(a)&&g(a,ATInternet.Tracker.pluginProtos[a])}},CallbacksManager=
function(a){var c={};this.init=function(){if(a.getConfig("activateCallbacks")){var e=a.getConfig("callbacks");(function(){if("undefined"!==typeof e&&e.include instanceof Array)for(var a=0;a<e.include.length;a++)ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(e.include[a])&&(c[e.include[a]]={"function":ATInternet.Callbacks[e.include[a]]},ATInternet.Tracker.callbackProtos[e.include[a]]||(ATInternet.Tracker.callbackProtos[e.include[a]]=c[e.include[a]]));else for(a in ATInternet.Callbacks)ATInternet.Callbacks.hasOwnProperty(a)&&
(c[a]={"function":ATInternet.Callbacks[a]},ATInternet.Tracker.callbackProtos[a]||(ATInternet.Tracker.callbackProtos[a]=c[a]));if("undefined"!==typeof e&&e.exclude instanceof Array)for(a=0;a<e.exclude.length;a++)c[e.exclude[a]]&&(c[e.exclude[a]]=void 0);for(var m in c)c.hasOwnProperty(m)&&c[m]&&k(m,c[m]["function"])})();ATInternet.Utils.addCallbackEvent(function(a){if(a.name){var c=!0;"undefined"!==typeof e&&(e.include instanceof Array&&-1===ATInternet.Utils.arrayIndexOf(e.include,a.name)&&(c=!1),
e.exclude instanceof Array&&-1!==ATInternet.Utils.arrayIndexOf(e.exclude,a.name)&&(c=!1));if(ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(a.name)){var g={};g[a.name]={"function":ATInternet.Callbacks[a.name]};c&&k(a.name,g[a.name]["function"]);ATInternet.Tracker.callbackProtos[a.name]||(ATInternet.Tracker.callbackProtos[a.name]=g[a.name])}}})}};var k=this.load=function(c,h){"function"===typeof h?(new h(a),a.emit("Tracker:Callback:Load:"+c+":Ok",{lvl:"INFO",details:{obj:h}})):a.emit("Tracker:Callback:Load:"+
c+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:h}});return a}},BufferManager=function(a){var c={};this.set=function(a,e,g){g=g||{};g.hitType=g.hitType||["page"];c[a]={value:e,options:g}};var k=function(a,c,g){return(a=window.ATInternet.Utils.cloneSimpleObject(a[c]))&&!g?a.value:a},e=function m(a,b){if(!(a&&b instanceof Array&&a instanceof Array))return[];if(0===a.length)return b;var e=a[0],d,f=[],r=window.ATInternet.Utils.cloneSimpleObject(a);r.shift();for(var q=0;q<b.length;q++)if("object"!==
typeof e[1])c[b[q]]&&c[b[q]].options[e[0]]===e[1]&&f.push(b[q]);else{d=e[1].length;for(var l=0;l<d;l++)if(c[b[q]]&&c[b[q]].options[e[0]]instanceof Array&&0<=window.ATInternet.Utils.arrayIndexOf(c[b[q]].options[e[0]],e[1][l])){f.push(b[q]);break}}return m(r,f)};this.get=function(a,g){var b={};if("string"===typeof a)b=k(c,a,g);else for(var n=e(a,window.ATInternet.Utils.getObjectKeys(c)),d=0;d<n.length;d++)b[n[d]]=k(c,n[d],g);return b};this.presentInFilters=function g(a,c){return a&&0!==a.length?a[0][0]===
c?!0:g(a.slice(1),c):!1};this.addInFilters=function b(a,d,f,c){if(!a||0===a.length)return c?[]:[[d,f]];var e=a[0][0],l=a[0][1];e===d&&(l instanceof Array&&!(-1<window.ATInternet.Utils.arrayIndexOf(l,f[0]))&&l.push(f[0]),c=!0);return[[e,l]].concat(b(a.slice(1),d,f,c))};this.del=function(a){c[a]=void 0};this.clear=function(){c={}}},Tag=function(a,c,k){c=c||{};var e=this;e.version="5.11.0";var h=window.ATInternet.Utils.cloneSimpleObject(c);e.triggers=new TriggersManager(e);e.emit=e.triggers.emit;e.onTrigger=
e.triggers.on;var m=window.ATInternet.Utils.cloneSimpleObject(dfltGlobalCfg)||{},g;for(g in a)a.hasOwnProperty(g)&&(m[g]=a[g]);e.getConfig=function(a){return m[a]};e.setConfig=function(a,c,d){void 0!==m[a]&&d||(e.emit("Tracker:Config:Set:"+a,{lvl:"INFO",details:{bef:m[a],aft:c}}),m[a]=c)};e.configPlugin=function(a,c,d){m[a]=m[a]||{};for(var f in c)c.hasOwnProperty(f)&&void 0===m[a][f]&&(m[a][f]=c[f]);d&&(d(m[a]),e.onTrigger("Tracker:Config:Set:"+a,function(a,b){d(b.details.aft)}));return m[a]};e.getContext=
function(a){return h[a]};e.setContext=function(a,c){e.emit("Tracker:Context:Set:"+a,{lvl:"INFO",details:{bef:h[a],aft:c}});h[a]=c};e.delContext=function(a,c){e.emit("Tracker:Context:Deleted:"+a+":"+c,{lvl:"INFO",details:{key1:a,key2:c}});if(a)h.hasOwnProperty(a)&&(c?h[a]&&h[a].hasOwnProperty(c)&&(h[a][c]=void 0):h[a]=void 0);else if(c)for(var d in h)h.hasOwnProperty(d)&&h[d]&&h[d].hasOwnProperty(c)&&(h[d][c]=void 0)};e.plugins=new PluginsManager(e);e.buffer=new BufferManager(e);e.setParam=e.buffer.set;
e.getParams=function(a){return e.buffer.get(a,!1)};e.getParam=e.buffer.get;e.delParam=e.buffer.del;e.builder=new BuildManager(e);e.sendHit=e.builder.send;e.sendUrl=e.builder.sendUrl;e.callbacks=new CallbacksManager(e);e.setParam("ts",function(){return(new Date).getTime()},{permanent:!0,hitType:["all"]});e.getConfig("disableCookie")&&e.setParam("idclient","xxxxxx-NO",{permanent:!0,hitType:["all"]});e.getConfig("medium")&&e.setParam("medium",e.getConfig("medium"),{permanent:!0,hitType:["all"]});e.plugins.init();
e.callbacks.init();ATInternet.Tracker.instances.push(e);e.emit("Tracker:Ready",{lvl:"INFO",msg:"Tracker initialized",details:{tracker:e,args:{config:a,context:c,callback:k}}});k&&k(e)};ATInternet.Tracker.Tag=Tag;ATInternet.Tracker.instances=[];ATInternet.Tracker.pluginProtos={};
ATInternet.Tracker.addPlugin=function(a,c){c=c||ATInternet.Tracker.Plugins[a];if(!ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=c;for(var k=0;k<ATInternet.Tracker.instances.length;k++)ATInternet.Tracker.instances[k].plugins.load(a,c)}};ATInternet.Tracker.delPlugin=function(a){if(ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=void 0;for(var c=0;c<ATInternet.Tracker.instances.length;c++)ATInternet.Tracker.instances[c].plugins.unload(a)}};
ATInternet.Tracker.callbackProtos={};
}).call(window);;(function(){var dfltPluginCfg={"lifetime":30,"lastPersistence":true,"listEventsForExec":[],"domainAttribution":true,"info":true};var dfltGlobalCfg={"visitLifetime":30,"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.Campaigns=function(a){a.setConfig("visitLifetime",dfltGlobalCfg.visitLifetime,!0);a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var c={},k,e;a.configPlugin("Campaigns",dfltPluginCfg||{},function(a){c=a});var h,m,g,b,n,d,f,r,q,l,p,u,z,y=function(b,f,l){var p=null;a.plugins.exec(b,f,l,function(a){p=a});return p},s=function(a,b){return y("Cookies",a,b)},v=function(a,b){return y("Utils",a,b)},x=function(a,b){var f=s(e,[a]);if(null!==f)return"object"===
typeof f&&!(f instanceof Array);s(k,[a,{},b]);return!0},A=function(b,f){var l=a.getContext("campaigns")||{};l[b]=f;a.setContext("campaigns",l)},w=function(y){k="set"+(c.domainAttribution?"":"Private");e="get"+(c.domainAttribution?"":"Private");h=s(e,[["atredir","gopc"]]);m=s(e,[["atredir","gopc_err"]]);g=s(e,[["atredir","camp"]]);s("del",[["atredir","gopc"]]);s("del",[["atredir","gopc_err"]]);s("del",[["atredir","camp"]]);b=s(e,[["atsession","histo_camp"]]);n=s(e,[["atreman","camp"]]);d=s(e,[["atreman",
"date"]]);var t=v("getLocation",[]);f=v("getQueryStringValue",["xtor",t]);r=v("getQueryStringValue",["xtdt",t]);q=v("getQueryStringValue",["xts",t]);l=a.getContext("forcedCampaign");p=!!a.getConfig("redirect");if(u=f&&r&&q?!0:!1)t=(new Date).getTime()/6E4,z=!p&&q!==a.getConfig("site")||0>t-r||t-r>=a.getConfig("visitLifetime")?!0:!1;t=l||g||f;p&&t&&x("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})&&(s(k,[["atredir","camp"],t]),s(k,[["atredir","gopc"],l?!1:g?h:u?!0:!1]),s(k,[["atredir",
"gopc_err"],l?!1:g?m:z?!0:!1]));!p&&n&&(A("xtor",n),t=(new Date).getTime()/36E5,t=Math.floor(t-d),A("roinbh",0<=t?t:0));p||(t=void 0,t=g?h?l||t:l||g:u?l||t:l||f||t,b&&b instanceof Array&&-1<b.indexOf(t)&&(t=void 0),t&&A("xto",t));if(!p&&!l){var w;g?m&&(w=g):z&&(w=f);w&&A("pgt",w)}p||!(w=g?l||g:l||f||void 0)||!l&&!g&&u&&z||!l&&g&&h&&m||((!b||b instanceof Array&&0>b.indexOf(w))&&x("atsession",{path:"/",session:60*a.getConfig("visitLifetime")})&&s(k,[["atsession","histo_camp"],b&&b.push(w)?b:[w]]),n&&
!c.lastPersistence||!x("atreman",{path:"/",session:86400*c.lifetime})||(s(k,[["atreman","camp"],w]),s(k,[["atreman","date"],(new Date).getTime()/36E5])));a.emit("Campaigns:"+y,{lvl:"INFO"})};(function(){var b=["Cookies","Utils"];if(-1===ATInternet.Utils.arrayIndexOf(a.getConfig("plgs"),"BackwardCompat"))a.plugins.waitForDependencies(b,function(){w("process2:done")});else a.onTrigger("BackCampaigns:process2:done",function(f,l){a.plugins.waitForDependencies(b,function(){w("process1:done")})},!0)})()};
window.ATInternet.Tracker.addPlugin("Campaigns");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Clicks=function(a){var c=function(a){var c="";switch(a){case "exit":c="S";break;case "download":c="T";break;case "action":c="A";break;case "navigation":c="N"}return c},k=function(c){var e=c.name;a.exec("Utils","manageChapters",[c,"chapter",3],function(a){e=a+(e?e:"")});return e},e=function(e){var m={p:k(e),s2:e.level2||"",click:c(e.type)||""},g=a.getContext("page")||{};m.pclick=k(g);m.s2click=g.level2||"";e.customObject&&a.exec("Utils","customObjectToString",[e.customObject],
function(a){m.stc=a});a.sendHit(m,[["hitType",["click"]]])};a.click={};a.clickListener=this.clickListener={};a.click.send=this.send=function(c){var m=!0;a.plugins.exec("TechClicks","manageClick",[c.elem,c.event,c.callback],function(a){m=a});e(c);return m};a.clickListener.send=this.clickListener.send=function(c){if(c.elem){var m;a.plugins.exec("TechClicks","isFormSubmit",[c.elem],function(a){m=a?"submit":"click"});ATInternet.Utils.addEvtListener(c.elem,m,function(g){a.plugins.exec("TechClicks","manageClick",
[c.elem,g,c.callback]);e(c)})}};a.click.set=this.set=function(e){a.dispatchSubscribe("click");a.setContext("click",{name:k(e),level2:e.level2||"",customObject:e.customObject});a.setParam("click",c(e.type)||"",{hitType:["click"]})};a.click.onDispatch=this.onDispatch=function(){var c={hitType:["click"]};a.setParam("p",a.getContext("click").name,c);a.setParam("s2",a.getContext("click").level2,c);var e=a.getContext("click").customObject;e&&a.setParam("stc",e,{hitType:["click"],encode:!0});e=a.getContext("page")||
{};a.setParam("pclick",k(e),c);a.setParam("s2click",e.level2||"",c);a.sendHit(null,[["hitType",["click"]]]);a.setContext("click",void 0)}};window.ATInternet.Tracker.addPlugin("Clicks");
}).call(window);;(function(){var dfltPluginCfg={"clientSideMode":"required","userIdCookieDuration":397,"userIdExpirationMode":"fixed","info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.ClientSideUserId=function(a){var c={},k=void 0,e=null,h=-1;a.configPlugin("ClientSideUserId",dfltPluginCfg||{},function(a){c=a});var m=function(){k=a.getContext("userIdentifier");a.exec("Cookies","get",["atuserid"],function(a){e=a})},g=function(f,c){n()?(a.setParam("idclient","OPT-OUT",{permanent:!0,hitType:["all"]}),b("atoptedout","OPT-OUT",!0)):(a.setParam("idclient",f,{permanent:!0,hitType:["all"]}),b("atuserid",f,c))},b=function(b,f,l){if("relative"===c.userIdExpirationMode||
"fixed"===c.userIdExpirationMode&&null===e||l){var p=new Date;p.setTime(p.getTime()+864E5*c.userIdCookieDuration);a.exec("Cookies","set",[b,f,{end:p,path:"/"}]);a.exec("Cookies","get",[b,!0],function(b){l||f===b||a.setParam("idclient",f+"-NO",{permanent:!0,hitType:["all"]})})}},n=function(){var b=!1,f=null,l=ATInternet.Utils.optedOut;!1===l&&a.exec("Cookies","set",["atoptedout",null,{path:"/"}]);a.exec("Cookies","get",["atoptedout",!0],function(a){f=a});if(!0===l||"OPT-OUT"===f)b=!0;return b},d=function(a){a&&
(a=a.detail)&&"clientsideuserid"===a.name&&a.id===h&&f()},f=function(){m();var b=!1;if("required"===c.clientSideMode){var f=navigator.userAgent;if(/Safari/.test(f)&&!/Chrome/.test(f)||/iPhone|iPod|iPad/.test(f))b=!0}else"always"===c.clientSideMode&&(b=!0);f="undefined"!==typeof k;if(b||f){var l="",l=f?k:null!==e?e:ATInternet.Utils.uuid().v4();g(l,f)}a.emit("ClientSideUserId:Ready",{lvl:"INFO",details:{clientSideMode:c.clientSideMode,userIdFromContext:k,userIdFromCookie:e,userId:l}})};(function(){a.plugins.waitForDependencies(["Cookies"],
function(){var a=ATInternet.Utils.uuid();h=parseInt(a.num(8));ATInternet.Utils.removeOptOutEvent(d);ATInternet.Utils.addOptOutEvent(d,h);f()})})();a.clientSideUserId={};a.clientSideUserId.set=function(a){g(a,!0)}};window.ATInternet.Tracker.addPlugin("ClientSideUserId");
}).call(window);;(function(){var dfltPluginCfg={"domainAttribution":true,"info":true};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.ContextVariables=function(a){var c="",k=null,e,h="",m="",g={};a.configPlugin("ContextVariables",dfltPluginCfg||{},function(a){g=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var b=function(b,f,c){var d=null;a.plugins.exec(b,f,c,function(a){d=a});return d},n=function(a,f){return b("Utils",a,f)},d=function(b,f){var c=null;a.plugins.exec("Cookies",b,f,function(a){c=a});return c},f=function(){a.setParam("hl",function(){var a=new Date;return a.getHours()+
"x"+a.getMinutes()+"x"+a.getSeconds()},{permanent:!0,hitType:["all"]})},r=function(a){var b="",b=e?e:"acc_dir"===c?"":null!=c?c:"acc_dir"===k?"":k?k:a.referrer;return b.replace(/[<>]/g,"").substring(0,1600).replace(/&/g,"$")};a.plugins.waitForDependencies(["Cookies","Utils"],function(){h="set"+(g.domainAttribution?"":"Private");m="get"+(g.domainAttribution?"":"Private");var b=n("getLocation",[]);c=n("getQueryStringValue",["xtref",b]);void 0===c&&(c="");e=a.getContext("forcedReferer");if(a.getConfig("redirect")){var b=
n("getDocumentLevel",[]),b=e?e:null!=c?c:b.referrer||"acc_dir",l;if(l=b){l={path:"/",end:a.getConfig("redirectionLifetime")};var p=d(m,["atredir"]);null!==p?l="object"===typeof p&&!(p instanceof Array):(d(h,["atredir",{},l]),l=!0)}l&&d(h,[["atredir","ref"],b])}else{k=d(m,[["atredir","ref"]]);d("del",[["atredir","ref"]]);a.setParam("vtag",a.version,{permanent:!0,hitType:["all"]});a.setParam("ptag","js",{permanent:!0,hitType:["all"]});b="";try{b+=window.screen.width+"x"+window.screen.height+"x"+window.screen.pixelDepth+
"x"+window.screen.colorDepth}catch(u){}a.setParam("r",b,{permanent:!0,hitType:["all"]});b="";window.innerWidth?b+=window.innerWidth+"x"+window.innerHeight:document.body&&document.body.offsetWidth&&(b+=document.body.offsetWidth+"x"+document.body.offsetHeight);a.setParam("re",b,{permanent:!0,hitType:["all"]});f();a.setParam("lng",navigator.language||navigator.userLanguage,{permanent:!0,hitType:["all"]});b=ATInternet.Utils.uuid().num(13);a.setParam("idp",b,{permanent:!0,hitType:["page","clickzone"]});
a.setParam("jv",navigator.javaEnabled()?"1":"0",{hitType:["page"]});b=n("getDocumentLevel",[]);a.setParam("ref",r(b),{permanent:!0,last:!0,hitType:["page"]})}a.emit("ContextVariables:Ready",{lvl:"INFO"})})};window.ATInternet.Tracker.addPlugin("ContextVariables");
}).call(window);;(function(){var dfltPluginCfg={"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Cookies=function(a){var c={},k={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var b="",f,c,d,e,g,h,n=0;for(a=k._utf8_encode(a);n<a.length;)f=a.charCodeAt(n++),c=a.charCodeAt(n++),d=a.charCodeAt(n++),e=f>>2,f=(f&3)<<4|c>>4,g=(c&15)<<2|d>>6,h=d&63,isNaN(c)?g=h=64:isNaN(d)&&(h=64),b=b+this._keyStr.charAt(e)+this._keyStr.charAt(f)+this._keyStr.charAt(g)+this._keyStr.charAt(h);return b},decode:function(a){var b="",f,c,d,
e,g,h=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");h<a.length;)f=this._keyStr.indexOf(a.charAt(h++)),c=this._keyStr.indexOf(a.charAt(h++)),e=this._keyStr.indexOf(a.charAt(h++)),g=this._keyStr.indexOf(a.charAt(h++)),f=f<<2|c>>4,c=(c&15)<<4|e>>2,d=(e&3)<<6|g,b+=String.fromCharCode(f),64!=e&&(b+=String.fromCharCode(c)),64!=g&&(b+=String.fromCharCode(d));return b=k._utf8_decode(b)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",f=0;f<a.length;f++){var c=a.charCodeAt(f);128>c?b+=String.fromCharCode(c):
(127<c&&2048>c?b+=String.fromCharCode(c>>6|192):(b+=String.fromCharCode(c>>12|224),b+=String.fromCharCode(c>>6&63|128)),b+=String.fromCharCode(c&63|128))}return b},_utf8_decode:function(a){for(var b="",f=0,c,d,e;f<a.length;)c=a.charCodeAt(f),128>c?(b+=String.fromCharCode(c),f++):191<c&&224>c?(d=a.charCodeAt(f+1),b+=String.fromCharCode((c&31)<<6|d&63),f+=2):(d=a.charCodeAt(f+1),e=a.charCodeAt(f+2),b+=String.fromCharCode((c&15)<<12|(d&63)<<6|e&63),f+=3);return b}},e=this.getCookie=function(b){return!a.getConfig("disableCookie")&&
b&&"string"===typeof b&&(b=RegExp("(?:^| )"+b+"=([^;]+)").exec(document.cookie)||null)?(b=b[1],b=a.getConfig("base64Storage")?k.decode(b):decodeURIComponent(b),b):null},h=this.setCookie=function(b,f,c){if(!a.getConfig("disableCookie")&&b&&"string"===typeof b&&"string"===typeof f){var d=a.getConfig("cookieDomain");b+="=";f=a.getConfig("base64Storage")?k.encode(f):encodeURIComponent(f);f=b+f;b=!1;if(c){b=c.secure;var e=c.end,g=c.domain;c=c.path;f+=e?"function"===typeof e.toGMTString?";expires="+e.toGMTString():
"number"===typeof e?";max-age="+e.toString():"":"";f=f+(d||g?";domain="+(g?g:d):"")+(c&&"string"===typeof c?";path="+c:"")}d=a.getConfig("cookieSecure")||b;f+=d&&"boolean"===typeof d?";secure":"";document.cookie=f;return!0}return null},m=function(a){var b=null;(a=e(a))&&(b=ATInternet.Utils.jsonParse(a));return b},g=function(a){return h(a.name,ATInternet.Utils.jsonSerialize(a),a.options)?a:null},b=function(a,b,f){var d=null;if(!f&&c[a])d=c[a];else if(d=m(a))d.options.session&&g(d),c[a]=d;return d?
b?(a=null,!d||"object"!==typeof d.val||d.val instanceof Array||void 0===d.val[b]||(a=d.val[b]),a):d.val:null},n=function(a,b,f,d){var e=null;if(b){if(e=m(a))d=e,!d||"object"!==typeof d.val||d.val instanceof Array?e=null:(d.val[b]=f,e=d),e&&(e=g(e))}else b=d=d||{},d={},d.name=a,d.val=f,b.session&&"number"===typeof b.session&&(b.end=b.session),d.options=b,e=g(d);e&&(c[a]=e);return e?e.val:null},d=function(a,b){b?n(a,b,void 0):(c[a]=void 0,h(a,"",{end:0}))},f=this.get=function(a,f){f=f||!1;return a instanceof
Array&&2===a.length?b(a[0],a[1],f):b(a,void 0,f)};this.getPrivate=function(b,c){c=c||!1;b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");return f(b,c)};var r=this.set=function(a,b,f){return a instanceof Array?n(a[0],a[1],b):n(a,null,b,f)};this.setPrivate=function(b,f,c){b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");return r(b,f,c)};var q=this.del=function(a){return a instanceof Array?d(a[0],a[1]):d(a)};this.delPrivate=function(b){b instanceof Array?b[0]+=a.getConfig("site"):
b+=a.getConfig("site");return q(b)};this.cacheInvalidation=function(){c={}}};window.ATInternet.Tracker.addPlugin("Cookies");
}).call(window);;(function(){var dfltPluginCfg={"lifetime":182,"domainAttribution":true,"info":true};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.IdentifiedVisitor=function(a){var c=null,k=null,e=null,h=null,m="",g="",b=null,n=null,d="",f="",r={};a.configPlugin("IdentifiedVisitor",dfltPluginCfg||{},function(a){r=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var q=function(b,f,c){var d=null;a.plugins.exec(b,f,c,function(a){d=a});return d},l=function(a,b){return q("Utils",a,b)},p=function(b,f){var c=null;a.plugins.exec("Cookies",b,f,function(a){c=a});return c},u=function(a,b){var c=
p(f,[a]);if(null!==c)return"object"===typeof c&&!(c instanceof Array);p(d,[a,{},b]);return!0},z=function(){var f=function(a,b){/-/.test(b)?(a.category=b.split("-")[0],a.id=b.split("-")[1]):a.id=b},d={category:"",id:""};f(d,g||n);var p={category:"",id:""};f(p,m||b);p.id?(p.category&&s("ac",p.category),s("at",p.id)):c&&a.setParam("at",c,{hitType:["all"],permanent:!0});d.id?(d.category&&s("ac",d.category),s("an",d.id)):k&&a.setParam("anc",e+"-"+k,{hitType:["all"],permanent:!0})},y=function(a,b){u("atidvisitor",
{path:"/",session:86400*r.lifetime})&&p(d,[["atidvisitor",a],b])},s=function(b,f){a.setParam(b,f,{hitType:["all"],permanent:!0});y(b,f)};a.plugins.waitForDependencies(["Cookies","Utils"],function(){d="set"+(r.domainAttribution?"":"Private");f="get"+(r.domainAttribution?"":"Private");var q=l("getLocation",[]);m=l("getQueryStringValue",["xtat",q]);g=l("getQueryStringValue",["xtan",q]);a.getConfig("redirect")?(m||g)&&u("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})&&(g&&p(d,[["atredir",
"an"],g]),m&&p(d,[["atredir","at"],m])):(b=p(f,[["atredir","at"]]),n=p(f,[["atredir","an"]]),p("del",[["atredir","at"]]),p("del",[["atredir","an"]]),c=p(f,[["atidvisitor","at"]]),k=p(f,[["atidvisitor","an"]]),e=p(f,[["atidvisitor","ac"]]),h=p(f,[["atidvisitor","vrn"]]),z(),q="-"+a.getConfig("site")+"-",RegExp(q).test(h)||(h=(h||"")+q,y("vrn",h),q=a.getContext("page")||{},q.vrn=1,a.setContext("page",q)));a.emit("IdentifiedVisitor:Ready",{lvl:"INFO",details:{cookieRedirectTextual:b,cookieRedirectNumeric:n,
cookieTextual:c,cookieNumeric:k,cookieCategory:e,cookieVrn:h}})});a.identifiedVisitor={};a.identifiedVisitor.set=this.set=function(a){var b=a.id;a=a.category;"number"===typeof b?s("an",b.toString()):s("at",b);"undefined"!==typeof a&&s("ac",a)};a.identifiedVisitor.unset=this.unset=function(){for(var b=["an","at","ac"],f=0;f<b.length;f++)a.exec("Cookies","set",[["atidvisitor",b[f]],void 0]),a.delParam(b[f]);a.delParam("anc")}};window.ATInternet.Tracker.addPlugin("IdentifiedVisitor");
}).call(window);;(function(){var dfltPluginCfg={"urlKeyword":"","urlResultPageNumber":"","urlResultPosition":"","info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.InternalSearch=function(a){var c={};a.configPlugin("InternalSearch",dfltPluginCfg||{},function(a){c=a});var k=function(c){var h={np:"undefined"!==typeof c.resultPageNumber?c.resultPageNumber:"1",click:"IS"};c.hasOwnProperty("keyword")&&(h.mc=c.keyword);c.hasOwnProperty("resultPosition")&&(h.mcrg=c.resultPosition);a.sendHit(h,[["hitType",["InternalSearch"]]])};a.internalSearch={};a.internalSearch.set=this.set=function(c){var h={},m=h;c.hasOwnProperty("keyword")&&(m.keyword=
c.keyword);m=h;c.hasOwnProperty("resultPageNumber")&&(m.resultPageNumber=c.resultPageNumber);c=a.getContext("InternalSearch")||{};h=ATInternet.Utils.completeFstLevelObj(h,c);"undefined"===typeof h.resultPageNumber&&(h.resultPageNumber="1");a.setContext("InternalSearch",h)};a.internalSearch.send=this.send=function(c){var h=!0;a.plugins.exec("TechClicks","manageClick",[c.elem,c.event,c.callback],function(a){h=a});k(c);return h};a.plugins.waitForDependencies(["Utils"],function(){var e;if(c.urlKeyword){var h=
document.location.href;e={};a.plugins.exec("Utils","getQueryStringValue",[c.urlKeyword,h],function(m){m&&(e.keyword=m);c.urlResultPageNumber&&a.plugins.exec("Utils","getQueryStringValue",[c.urlResultPageNumber,h],function(a){e.resultPageNumber=a||"1"})})}e&&a.setContext("InternalSearch",e);a.emit("InternalSearch:Ready",{lvl:"INFO",details:{config:{urlKeyword:c.urlKeyword,urlResultPageNumber:c.urlResultPageNumber},url:h,data:e}})})};window.ATInternet.Tracker.addPlugin("InternalSearch");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.OnSiteAds=function(a){var c="",k=function(b){var c=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){c=a+(c?c:"")});return c},e=function(a,b){return a[b]?a[b]:""},h=function(a,b){var c=e(a,b);if(c){var d=e(a,"prefix");if(c.campaignId){var d=d||"PUB",g=e(c,"campaignId"),h=e(c,"creation"),n=e(c,"variant"),m=e(c,"format"),k=e(c,"generalPlacement"),v=e(c,"detailedPlacement"),x=e(c,"advertiserId"),c=e(c,"url");return d+"-"+g+"-"+h+"-"+n+"-"+m+"-"+k+"-"+
v+"-"+x+"-"+c}if(c.adId)return d=d||"INT",g=e(c,"adId"),h=e(c,"format"),c=e(c,"productId"),d+"-"+g+"-"+h+"||"+c}},m=function(b){var c=a.getContext("page")||{};a.sendHit({atc:h(b,"click"),type:"AT",patc:k(c),s2atc:c.level2||"",stc:b.customObject||""},[["hitType",["onSiteAdsClick"]]])},g=function(b){a.sendHit({ati:h(b,"impression"),type:"AT",stc:b.customObject||""},[["hitType",["onSiteAdsImpression"]]])},b=function(b,c){var d=a.buffer.get("ati",!0)||{};d.value="string"===typeof d.value?[d.value]:d.value||
[];d.options=d.options||{hitType:[c,"page"]};d.value.push(b);a.buffer.set("ati",d.value,d.options)},n=function(b,c){b.click?a.setParam("atc",h(b,"click"),{hitType:[c,"page"]}):b.impression&&a.setParam("ati",h(b,"impression"),{hitType:[c,"page"]});if(b.customObject){a.setContext("onsiteads",{customObject:b.customObject});var d=a.getContext("page")||{};d.customObject=ATInternet.Utils.completeFstLevelObj(d.customObject,b.customObject,!1);a.setContext("page",d)}a.dispatchSubscribe("onSiteAds")};a.selfPromotion=
this.selfPromotion={};a.publisher=this.publisher={};a.publisher.set=this.publisher.set=function(a){n(a,"publisher")};a.selfPromotion.set=this.selfPromotion.set=function(a){n(a,"selfPromotion")};a.publisher.add=this.publisher.add=function(c){b(h(c,"impression"),"publisher");a.dispatchSubscribe("onSiteAds")};a.selfPromotion.add=this.selfPromotion.add=function(c){b(h(c,"impression"),"selfPromotion");a.dispatchSubscribe("onSiteAds")};var d=this.advertEvent=function(b){var c=!0;a.exec("TechClicks","manageClick",
[b.elem,b.event,b.callback],function(a){c=a});b.click?m(b):b.impression&&g(b);return c};a.publisher.send=this.publisher.send=function(a){return d(a)};a.selfPromotion.send=this.selfPromotion.send=function(a){return d(a)};a.onSiteAds={};a.onSiteAds.onDispatch=this.onDispatch=function(){if(!a.dispatchSubscribed("page")){var b=a.getContext("page")||{};a.setParam("type","AT",{hitType:["publisher","selfPromotion"]});a.getParam("atc")&&(a.setParam("patc",k(b),{hitType:["publisher","selfPromotion"]}),a.setParam("s2atc",
b.level2||"",{hitType:["publisher","selfPromotion"]}));(b=a.getContext("onsiteads"))&&b.customObject&&a.setParam("stc",b.customObject,{encode:!0,hitType:["publisher","selfPromotion"]});a.sendHit(null,[["hitType",["publisher","selfPromotion"]]])}};a.plugins.waitForDependencies(["Utils","TechClicks"],function(){c=document.location.href;a.plugins.exec("Utils","getQueryStringValue",["xtatc",c],function(b){b&&a.setParam("atc",b,{hitType:["publisher","selfPromotion","page"]})});a.emit("OnSiteAds:Ready",
{lvl:"INFO",details:{href:c}})})};window.ATInternet.Tracker.addPlugin("OnSiteAds");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Page=function(a){var c=["pageId","chapterLabel","update"],k=["pid","pchap","pidt"],e=["page","site"],h=["f","x"],m=function(b){var c=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){c=a+(c?c:"")});return c},g=function(a,b,c){b?a=b:a||"undefined"===typeof c||(a=c);return a},b=function(a,b,c){b.hasOwnProperty(c)&&(a[c]=g(a[c],b[c]))},n=function(b){if(!ATInternet.Utils.isPreview()||a.getConfig("preview"))ATInternet.Utils.isPrerender(function(a){b(a)})||
b()},d=function(b,c,f){if(c)for(var d=0;d<e.length;d++)if(c.hasOwnProperty(e[d])&&c[e[d]])for(var g in c[e[d]])c[e[d]].hasOwnProperty(g)&&(f?b[h[d]+g]=c[e[d]][g]:a.setParam(h[d]+g,c[e[d]][g]))},f=function(b,f,d){if(f){a.exec("Utils","manageChapters",[f,"chapter",3],function(a){a&&(f.chapterLabel=a.replace(/::$/gi,""))});for(var e=0;e<k.length;e++)f.hasOwnProperty(c[e])&&(d?b[k[e]]=f[c[e]]:a.setParam(k[e],f[c[e]]))}},r=function(b,c,f){if(c&&c.keywords instanceof Array){var d=c.keywords.length;if(0<
d){for(var e="",g=0;g<d;g++)e+="["+c.keywords[g]+"]"+(g<d-1?"|":"");f?b.tag=e:a.setParam("tag",e)}}},q=function(b,c,f){if(c){var d,e=function(a){return a?a:"0"};d=""+(e(c.category1)+"-");d+=e(c.category2)+"-";d+=e(c.category3);f?b.ptype=d:a.setParam("ptype",d)}},l=function(b,c,f){if(c)for(var d in c)c.hasOwnProperty(d)&&"undefined"!==typeof c[d]&&(f?b[d]=c[d]:a.setParam(d,c[d]))};a.customVars=this.customVars={};a.customVars.set=this.customVars.set=function(b){var c=a.getContext("page")||{},f=c.customVars;
if(f){if(b)for(var d in b)b.hasOwnProperty(d)&&(f[d]=ATInternet.Utils.completeFstLevelObj(f[d],b[d],!0))}else f=b;c.customVars=f;a.setContext("page",c)};a.dynamicLabel=this.dynamicLabel={};a.dynamicLabel.set=this.dynamicLabel.set=function(b){var c=a.getContext("page")||{};c.dynamicLabel=ATInternet.Utils.completeFstLevelObj(c.dynamicLabel,b,!0);a.setContext("page",c)};a.tags=this.tags={};a.tags.set=this.tags.set=function(b){var c=a.getContext("page")||{};c.tags=ATInternet.Utils.completeFstLevelObj(c.tags,
b,!0);a.setContext("page",c)};a.customTreeStructure=this.customTreeStructure={};a.customTreeStructure.set=this.customTreeStructure.set=function(b){var c=a.getContext("page")||{};c.customTreeStructure=ATInternet.Utils.completeFstLevelObj(c.customTreeStructure,b,!0);a.setContext("page",c)};a.page={};a.page.reset=this.reset=function(){a.setContext("page",void 0)};a.page.set=this.set=function(c){a.dispatchSubscribe("page");var f=a.getContext("page")||{};f.name=g(f.name,c.name,"");f.level2=g(f.level2,
c.level2,"");b(f,c,"chapter1");b(f,c,"chapter2");b(f,c,"chapter3");f.customObject=ATInternet.Utils.completeFstLevelObj(f.customObject,c.customObject,!0);a.setContext("page",f)};a.page.send=this.send=function(c){var e={p:m(c),s2:c.level2||""},h=!0,k=c.customObject;if(k){var s=a.getParam("stc",!0);if(s&&s.options.permanent){var v=s?s.options.hitType:[],x=ATInternet.Utils.arrayIndexOf;if(-1!=x(v,"page")||-1!=x(v,"all"))k=ATInternet.Utils.completeFstLevelObj(s.value||{},k,!0)}a.exec("Utils","customObjectToString",
[k],function(a){e.stc=a})}k=a.getContext("page")||{};k.vrn&&(e.vrn=k.vrn,k.vrn=void 0,a.setContext("page",k));s=a.getContext("InternalSearch")||{};"undefined"!=typeof s.keyword&&(e.mc=ATInternet.Utils.cloneSimpleObject(s.keyword),"undefined"!=typeof s.resultPageNumber&&(e.np=ATInternet.Utils.cloneSimpleObject(s.resultPageNumber)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&(e.pvw=1);d(e,c.customVars,!0);f(e,c.dynamicLabel,!0);r(e,c.tags,!0);q(e,c.customTreeStructure,
!0);s=a.getContext("campaigns")||{};l(e,s,!0);a.setContext("campaigns",void 0);a.exec("TechClicks","manageClick",[c.elem,c.event,c.callback],function(a){h=a});n(function(){a.sendHit(e)});k.name=g(k.name,c.name,"");k.level2=g(k.level2,c.level2,"");b(k,c,"chapter1");b(k,c,"chapter2");b(k,c,"chapter3");a.setContext("page",k);return h};a.page.onDispatch=this.onDispatch=function(){var b=a.getContext("page")||{},c=a.getContext("InternalSearch")||{};a.setParam("p",m(b));a.setParam("s2",b.level2||"");b.vrn&&
(a.setParam("vrn",b.vrn),b.vrn=void 0,a.setContext("page",b));"undefined"!=typeof c.keyword&&(a.setParam("mc",ATInternet.Utils.cloneSimpleObject(c.keyword)),"undefined"!=typeof c.resultPageNumber&&a.setParam("np",ATInternet.Utils.cloneSimpleObject(c.resultPageNumber)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&a.setParam("pvw",1);d(null,b.customVars,!1);f(null,b.dynamicLabel,!1);r(null,b.tags,!1);q(null,b.customTreeStructure,!1);c=a.getContext("campaigns")||
{};l(null,c,!1);a.setContext("campaigns",void 0);var b=b.customObject,e=[["hitType",["page"]]];if(b)if(c=a.getParam("stc",!0)){var g=c.options.hitType||[],h=ATInternet.Utils.arrayIndexOf,h=-1!=h(g,"page")||-1!=h(g,"all"),g=c.options.permanent;h?(h=ATInternet.Utils.cloneSimpleObject(c),h.value=ATInternet.Utils.completeFstLevelObj(h.value||{},b,!0),a.setParam("stc",h.value,{encode:!0}),n(function(){a.sendHit(null,e)}),g&&a.setParam("stc",c.value,c.options)):(a.setParam("stc",b,{encode:!0}),n(function(){a.sendHit(null,
e)}),a.setParam("stc",c.value,c.options))}else a.setParam("stc",b,{encode:!0}),n(function(){a.sendHit(null,e)});else n(function(){a.sendHit(null,e)})}};window.ATInternet.Tracker.addPlugin("Page");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.SalesTracker=function(a){var c=function(b,c,d){b.hasOwnProperty(d)&&(b=b[d],a.setParam(c,void 0===b?"":b+"",{hitType:["page"]}))},k=function(a){for(var c in a)if(a.hasOwnProperty(c))return!1;return!0},e=function(a){return"object"===typeof a&&!(a instanceof Array)},h=function(b){var c="";a.exec("Utils","manageChapters",[b,"category",6],function(a){a&&(c=a)});c+=b.productId;b=a.getContext("product")||{};b.viewedProducts?b.viewedProducts.push(c):b.viewedProducts=[c];
a.setContext("product",b)},m=0,g=function(b){var c=b.productId?b.productId:"",d=b.category?b.category+"::":"";a.exec("Utils","manageChapters",[b,"category",6],function(a){a&&(d=a)});return d+c};a.order=this.order={};a.cart=this.cart={};a.aisle=this.aisle={};a.salesTracker={};a.product=this.product={};a.order.set=this.order.set=function(b){var g=!1;if(e(b)&&!k(b)){g=!0;a.dispatchSubscribe("page");a.dispatchSubscribe("salesTracker");c(b,"cmd","orderId");c(b,"roimt","turnover");c(b,"st","status");"boolean"===
typeof b.newCustomer?a.setParam("newcus",b.newCustomer?"1":"0",{hitType:["page"]}):b.newCustomer&&"undefined"===typeof a.getParams("newcus")&&a.setParam("newcus","0",{hitType:["page"]});var d=b.amount;e(d)&&(c(d,"mtht","amountTaxFree"),c(d,"mtttc","amountTaxIncluded"),c(d,"tax","taxAmount"));d=b.delivery;e(d)&&(c(d,"fp","shippingFeesTaxIncluded"),c(d,"fpht","shippingFeesTaxFree"),c(d,"dl","deliveryMethod"));c(b,"mp","paymentMethod");d=b.discount;e(d)&&(c(d,"dsc","discountTaxIncluded"),c(d,"dscht",
"discountTaxFree"),c(d,"pcd","promotionalCode"));"boolean"===typeof b.confirmationRequired?a.setParam("tp",b.confirmationRequired?"pre1":"",{hitType:["page"]}):b.confirmationRequired&&"undefined"===typeof a.getParams("tp")&&a.setParam("tp","",{hitType:["page"]});b=b.orderCustomVariables;if(b instanceof Array)for(d=0;d<b.length;d++)c(b,"o"+(d+1),d)}return g};a.cart.set=this.cart.set=function(b){var g=!1;e(b)&&!k(b)&&(g=!0,a.dispatchSubscribe("page"),a.dispatchSubscribe("salesTracker"),c(b,"idcart",
"cartId"),"boolean"===typeof b.isBasketPage?"pre1"!==a.getParams("tp")&&a.setParam("tp",b.isBasketPage?"cart":"",{hitType:["page"]}):b.isBasketPage&&"undefined"===typeof a.getParams("tp")&&a.setParam("tp","",{hitType:["page"]}));return g};a.cart.add=this.cart.add=function(b){var h=!1;if(e(b)&&!k(b)&&(h=!0,b=b.product,e(b))){m++;var d=m,f=g(b);a.setParam("pdt"+d,f,{hitType:["page"]});c(b,"qte"+d,"quantity");c(b,"mt"+d,"unitPriceTaxIncluded");c(b,"mtht"+d,"unitPriceTaxFree");c(b,"dsc"+d,"discountTaxIncluded");
c(b,"dscht"+d,"discountTaxFree");c(b,"pcode"+d,"promotionalCode")}return h};a.aisle.set=this.aisle.set=function(b){var c=!1;if(e(b)&&!k(b)){c=!0;a.dispatchSubscribe("page");var d="";a.exec("Utils","manageChapters",[b,"level",6],function(a){d=a});d=d.replace(/::$/gi,"");a.setParam("aisl",d,{hitType:["page"]})}return c};a.product.add=this.product.add=function(b){var c=!1,d;if(d=e(b))if(d=!k(b)){a:{d=["productId"];for(var f=0;f<d.length;f++)if(void 0===b[d[f]]){d=!0;break a}d=!1}d=!d}d&&(c=!0,h(b),a.dispatchSubscribe("salesTracker"));
return c};a.salesTracker.onDispatch=this.onDispatch=function(){a.getParams("cmd");a.getParams("idcart")||"cart"!==a.getParams("tp")&&a.getParams("tp");var b=a.getContext("product");b&&b.viewedProducts&&0<b.viewedProducts.length&&(a.setParam("pdtl",b.viewedProducts.join("|"),{hitType:["product"]}),a.setParam("type","pdt",{hitType:["product"]}),a.sendHit(null,[["hitType",["product"]]]))}};window.ATInternet.Tracker.addPlugin("SalesTracker");
}).call(window);;(function(){var dfltPluginCfg={"clicksAutoManagementEnabled":true,"clicksAutoManagementTimeout":500,"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.TechClicks=function(a){var c,k;a.configPlugin("TechClicks",dfltPluginCfg||{},function(a){c=a.clicksAutoManagementEnabled;k=a.clicksAutoManagementTimeout});this.deactivateAutoManagement=function(){c=!1};var e=function(a){switch(a.target){case "_top":window.top.location.href=a.url;break;case "_parent":window.parent.location.href=a.url;break;default:window.location.href=a.url}},h=function(a){var b=a.timeout;a.mailto?setTimeout(function(){window.location.href=a.mailto},
b):a.form?setTimeout(function(){a.form.submit()},b):a.url&&setTimeout(function(){e({url:a.url,target:a.target})},b)},m=function(b){for(var c,g="_self",m=b.timeoutonly;b;){if(b.href&&0===b.href.indexOf("http")){c=b.href.split('"').join('\\"');g=b.target?b.target:g;break}b=b.parentNode}if(c){if(!m)a.onTrigger("Tracker:Hit:Sent:Ok",function(){e({url:c,target:g})});h({url:c,target:g,timeout:k})}},g=function(b){var c=b;for(b=c.timeoutonly;c&&"FORM"!==c.nodeName;)c=c.parentNode;if(c){if(!b)a.onTrigger("Tracker:Hit:Sent:Ok",
function(){c.submit()});h({form:c,timeout:k})}},b=function(b){var c=b;for(b=c.timeoutonly;c&&!(c.href&&0<=c.href.indexOf("mailto:"));)c=c.parentNode;if(c){if(!b)a.onTrigger("Tracker:Hit:Sent:Ok",function(){window.location.href=c.href});h({mailto:c.href,timeout:k})}},n=function(a){for(;a;){if(a.href){if(0<=a.href.indexOf("mailto:"))return"mailto";if(0===a.href.indexOf("http"))return"redirection"}else if("FORM"===a.nodeName)return"form";a=a.parentNode}return!1};this.manageClick=function(a,e,h){var k=
!0;if(c&&a){var l;a:{for(l=a;l;){if("function"===typeof l.getAttribute&&("_blank"===l.getAttribute("target")||"no"===l.getAttribute("data-atclickmanagement"))){l=!0;break a}l=l.parentNode}l=a;for(var p=window.location.href,u;l;){if((u=l.href)&&0<u.indexOf("#")&&p.substring(0,0<p.indexOf("#")?p.indexOf("#"):p.length)===u.substring(0,u.indexOf("#"))){l=!0;break a}l=l.parentNode}l=!1}p=n(a);if(!l&&p)switch(p){case "mailto":b(a);k=!1;break;case "form":g(a);k=!1;break;case "redirection":m(a),k=!1}}e&&
(a=e.defaultPrevented,"function"===typeof e.isDefaultPrevented&&(a=e.isDefaultPrevented()),a||e.preventDefault&&e.preventDefault());h&&h();return k}};window.ATInternet.Tracker.addPlugin("TechClicks");
}).call(window);;(function(){var dfltPluginCfg={"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Utils=function(a){var c=this,k={};c.getQueryStringValue=function(a,c){var e=window.ATInternet.Utils.hashcode(c).toString();if(!k[e]){k[e]={};var b=RegExp("[&#?]{1}([^&=#?]*)=([^&#]*)?","g"),n=b.exec(c);if(null!==n)for(;null!==n;)k[e][n[1]]=n[2],n=b.exec(c)}return k[e].hasOwnProperty(a)?k[e][a]:null};c.customObjectToString=function(a){return encodeURIComponent(window.ATInternet.Utils.jsonSerialize(a))};c.manageChapters=function(c,e,g){var b=a.getConfig("ignoreEmptyChapterValue"),
k="";if(c){g=parseInt(g,10);for(var d=1;d<g+1;d++)var f=c[e+d]||"",k=b?k+(f?f+"::":""):k+(c.hasOwnProperty(e+d)?f+"::":"")}return k};c.getDocumentLevel=function(){var c=a.getConfig("documentLevel");if(0>c.indexOf("."))return window[c]||document;c=c.split(".");return window[c[0]][c[1]]||document};c.getLocation=function(){return c.getDocumentLevel().location.href};a.dispatchIndex={};a.dispatchStack=[];a.dispatchEventFor={};var e=0;a.dispatchSubscribe=function(c){return a.dispatchIndex[c]?!1:(a.dispatchStack.push(c),
a.dispatchIndex[c]=!0)};a.dispatchSubscribed=function(c){return!0===a.dispatchIndex[c]};a.addSpecificDispatchEventFor=function(c){return a.dispatchEventFor[c]?!1:(a.dispatchEventFor[c]=!0,e++,!0)};a.processSpecificDispatchEventFor=function(c){a.dispatchEventFor[c]&&(a.dispatchEventFor[c]=!1,e--,0===e&&(a.dispatchEventFor={},a.emit("Tracker:Plugin:SpecificEvent:Exec:Complete",{lvl:"INFO"})))};a.dispatch=function(){var c=function(){for(;0<a.dispatchStack.length;){var c=a.dispatchStack.pop();a[c].onDispatch()}a.dispatchIndex=
{};a.delContext(void 0,"customObject")},k=function(){if(a.plugins.isExecWaitingLazyloading())a.onTrigger("Tracker:Plugin:Lazyload:Exec:Complete",function(){c()},!0);else c()};if(0===e)k();else a.onTrigger("Tracker:Plugin:SpecificEvent:Exec:Complete",function(){k()},!0)};a.dispatchRedirect=function(c){var e=!0;c&&c.elem&&(c.elem.timeoutonly=!0,a.plugins.exec("TechClicks","manageClick",[c.elem,c.event,c.callback],function(a){e=a}));a.dispatch();return e}};window.ATInternet.Tracker.addPlugin("Utils");
}).call(window);
if(typeof window.ATInternet.onTrackerLoad==='function'){window.ATInternet.onTrackerLoad();}